# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "pata_atiixp" "usb_storage" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/879668d8-390f-49e5-ad62-2410ccf1329c";
      fsType = "btrfs";
      options = [ "subvol=@nixos" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/879668d8-390f-49e5-ad62-2410ccf1329c";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/arch" =
    { device = "/dev/disk/by-uuid/879668d8-390f-49e5-ad62-2410ccf1329c";
      fsType = "btrfs";
      options = [ "subvol=@arch" ];
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/07fd113d-e50c-408c-91e3-a05d04e43f41";
      fsType = "ext4";
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-uuid/879668d8-390f-49e5-ad62-2410ccf1329c";
      fsType = "btrfs";
      options = [ "subvol=@docker" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6584-BFAC";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/879668d8-390f-49e5-ad62-2410ccf1329c";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  #swapDevices =
  #  [ { device = "/dev/disk/by-uuid/298a52b3-be6b-48b7-b7f5-838e42935f0c"; }
  #  ];

  nix.maxJobs = lib.mkDefault 4;
}
