# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "zpool/nixos/root";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "zpool/nixos/nix";
    fsType = "zfs";
  };

  fileSystems."/root" = {
    device = "zpool/userdata/root";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/98F4-69A2";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/home/sam" = {
    device = "zpool/userdata/sam";
    fsType = "zfs";
  };

  fileSystems."/home/aidan" = {
    device = "zpool/userdata/aidan";
    fsType = "zfs";
  };

  fileSystems."/home/jacob" = {
    device = "zpool/userdata/jacob";
    fsType = "zfs";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/308fd4ad-8e4e-4eeb-87aa-7a328a593f41";}
    {device = "/dev/disk/by-uuid/59178c15-39dc-4c6a-a3d2-12704bdff83c";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
