#manually set free authentication URL list of facebook, max 32 URLS
#eap.fap.fb.enable=false
#eap.fap.fb.urls=example1.com, example2.com, example3.com

#omada config
omadac.type=linux

#web config
# After Omada Controller is initialized, the configuration of the following ports will be overwritten.
# If you want to change their configurations, please configure them in the controller software.
manage.http.port=8088
manage.https.port=8043
portal.http.port=8088
portal.https.port=8843
upgrade.https.port=8043

portal.logout.domain=portal.tplink.net

#mongo config
# Paths are relative to the working directory (OMADA_HOME/lib), so ../data resolves to OMADA_HOME/data
eap.mongod.db=../data/db
eap.mongod.port=27217
eap.mongod.pid.path=../data/mongo.pid
eap.mongod.host=127.0.0.1
eap.mongod.bind.arg=--bind_ip
eap.mongod.args=--port ${eap.mongod.port} --dbpath "${eap.mongod.db}" -pidfilepath "${eap.mongod.pid.path}" --logappend --logpath "../logs/mongod.log" --networkMessageCompressors snappy
eap.mongod.repair.command=--repair --dbpath "${eap.mongod.db}" --logappend --logpath "../logs/mongod.log"

#limit the size of mongodb log, unit is MB.
eap.mongod.log.size.limit=512
eap.mongod.log.rolling.size=50

##enable mongodb journaling in linux
linux.mongod.nojournal=false

# net config
discovery.net.thread=2
max.discovery.net.thread=10
discovery.net.queue.size=150

# monitor config
max.device.adopt.each.batch=100

portal.sender.thread.num=4

max.device=3000

adopt.device.manage.config.maxAdoptSyncNum=5
adopt.device.manage.config.reconnectMaxAdoptSyncNum=10

upgrade.max.sending.file.device.count=10

client.portal.auth.config.authNumPerSecond=90
port.app.discovery=27001
port.adopt.v1=29812
port.upgrade.v1=29813
port.manager.v1=29811
port.manager.v2=29814
port.discovery=29810
port.transfer.v2=29815
port.rtty=29816
port.olt.discovery=19810
port.device.monitor=29817

html.dir=../data/html/

# sso config
sso.saml.redirectUrl=https://localhost:8043/
sso.saml.signOnUrl=https://localhost:8043/sso/saml/login
sso.saml.entityUrl=https://localhost:8043/

# This command is used to globally control whether users can select the default VLAN(SSID, AP Management VLAN)
allow_select_default_vlan=false

auto.backup.dataExport.batchLimit=500000

need.client.real-time.cluster.sync=true

client.cluster.sync.interval.second=30
