# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  hardware.enableRedistributableFirmware = lib.mkDefault true;

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "pata_atiixp" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "zroot/root/nixos";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/0A70-078F";
      fsType = "vfat";
    };

  fileSystems."/var" =
    {
      device = "zroot/var";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    {
      device = "zroot/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    {
      device = "zroot/home";
      fsType = "zfs";
    };

  fileSystems."/data" =
    {
      device = "zdata/data";
      fsType = "zfs";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/4c8f1655-ec84-45fa-9ef6-d34453d95d6b"; }];

  nix.settings.max-jobs = lib.mkDefault 8;
}
