# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  ...
}: {
  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.kernelModules = ["kvm-intel" "wl"];

  fileSystems."/" = {
    device = "sarov/root";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "sarov/home";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "sarov/nix";
    fsType = "zfs";
  };

  fileSystems."/iog" = {
    device = "sarov/iog";
    fsType = "zfs";
    options = ["noauto"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/67E3-17ED";
    fsType = "vfat";
  };

  swapDevices = [{device = "/dev/disk/by-uuid/a76f74a6-d2ab-4b71-8514-5e7faa14f3dd";}];

  nix.settings.max-jobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
