# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).
{
  config,
  system,
  pkgs,
  lib,
  inputs,
  ...
}: {
  deployment = {
    targetHost = "10.40.33.21";
    targetPort = 22;
    targetUser = "root";
  };

  sops.defaultSopsFile = ./secrets.yaml;
  sops.secrets.pool_opcert = {};
  sops.secrets.pool_vrf_skey = {};
  sops.secrets.pool_kes_skey = {};

  # Use the systemd-boot EFI boot loader.
  boot = {
    kernel.sysctl = {
      "net.ipv4.conf.all.forwarding" = true;
    };
    loader.grub = {
      device = "nodev";
      efiSupport = true;
    };
    initrd = {
      availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sdhci_acpi"];
      kernelModules = [];
    };
    kernelModules = ["amdgpu" "kvm-amd"];
    extraModulePackages = [];
  };

  nix = {
    settings.sandbox = true;
    settings.cores = 4;
    settings.substituters = ["https://cache.nixos.org" "https://cache.iog.io"];
    settings.trusted-public-keys = ["hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ="];
    extraOptions = ''
      experimental-features = nix-command flakes fetch-closure
    '';
  };

  nixpkgs.overlays = [
    inputs.niri.overlays.niri
  ];
  nixpkgs.config.allowUnfree = true;
  networking = {
    hostName = "valaam";
    hostId = "07c7b2e8";
    tempAddresses = "disabled";
    bridges = {
      br0 = {
        interfaces = ["enp4s0"];
      };
    };
    useDHCP = false;
    interfaces.br0.mtu = 1492;
    interfaces.br0.useDHCP = true;
    interfaces.wlp3s0.useDHCP = true;
    networkmanager.enable = false;
    # TODO: remove when working
    #nat = {
    #  enable = true;
    #  internalInterfaces = [ "ve-+" ];
    #  externalInterface = "mv-enp4s0-host";
    #};
    #wireless = {
    #  enable = true;
    #  networks = secrets.wifiNetworks;
    #};
  };

  time.timeZone = "GMT";

  fonts.fontDir.enable = true;
  fonts.enableGhostscriptFonts = true;
  fonts.packages = with pkgs; [
    # Used by starship for fonts
    nerd-fonts.fira-code
    corefonts
    fira # monospaced
    fira-code
    powerline-fonts
    inconsolata
    liberation_ttf
    dejavu_fonts
    bakoma_ttf
    gentium
    ubuntu-classic
    terminus_font
    unifont # some international languages
  ];

  environment = {
    etc = {
      "per-user/sam/gitconfig".text = import ../../sam-dotfiles/git-config.nix;
      "sway/config".source = ../../sam-dotfiles/sway/config;
      "per-user/sam/wezterm.lua".source = ../../sam-dotfiles/wezterm.lua;
      "xdg/waybar/config".source = ../../sam-dotfiles/waybar/config;
      "xdg/waybar/style.css".source = ../../sam-dotfiles/waybar/style.css;
      "sysconfig/lm_sensors".text = ''
        # Generated by sensors-detect on Tue Feb 15 13:12:56 2022
        # This file is sourced by /etc/init.d/lm_sensors and defines the modules to
        # be loaded/unloaded.
        #
        # The format of this file is a shell script that simply defines variables:
        # HWMON_MODULES for hardware monitoring driver modules, and optionally
        # BUS_MODULES for any required bus driver module (for example for I2C or SPI).

        HWMON_MODULES="coretemp"
      '';
    };

    shellInit = ''
      export GPG_TTY="$(tty)"
      gpg-connect-agent /bye
      export SSH_AUTH_SOCK="/run/user/$UID/gnupg/S.gpg-agent.ssh"
    '';
  };

  environment.systemPackages = with pkgs; [
    inputs.home-manager.packages.x86_64-linux.home-manager
    inputs.shadowharvester.packages.x86_64-linux.shadow-harvester
    google-chrome
    wget
    vim
    screen
    gitMinimal
    pinentry-gtk2
    gnupg
    python3Packages.ipython
    srm
    jq
    steamcmd
    wineWowPackages.waylandFull
    winetricks
    starship
  ];

  programs = {
    ssh.startAgent = lib.mkForce false;
    gnupg.agent = {
      enable = true;
      enableSSHSupport = true;
      pinentryPackage = pkgs.pinentry-gtk2;
    };
    mosh.enable = true;
    bash = {
      interactiveShellInit = ''
        eval "$(direnv hook bash)"
        eval "$(starship init bash)"
      '';
    };
    hyprland = {
      enable = true;
      xwayland.enable = true;
    };
    niri = {
      enable = true;
      package = pkgs.niri-unstable;
    };
    sway = {
      enable = true;
    };
  };

  services = {
    wled-sequencer = {
      enable = true;
      package = inputs.wled-sequencer.packages.${pkgs.stdenv.hostPlatform.system}.wled-sequencer;
      settings = {
      	host = "10.40.8.61";
	file = "/var/lib/wled-sequencer/christmas-light-show-2025.fseq";
      };
    };
    udev.extraRules = let
      dependencies = with pkgs; [coreutils gnupg gawk gnugrep];
      clearYubikey = pkgs.writeScript "clear-yubikey" ''
        #!${pkgs.stdenv.shell}
        export PATH=${pkgs.lib.makeBinPath dependencies};
        keygrips=$(
          gpg-connect-agent 'keyinfo --list' /bye 2>/dev/null \
            | grep -v OK \
            | awk '{if ($4 == "T") { print $3 ".key" }}')
        for f in $keygrips; do
          rm -v ~/.gnupg/private-keys-v1.d/$f
        done
        gpg --card-status 2>/dev/null 1>/dev/null || true
      '';
      clearYubikeySam = pkgs.writeScript "clear-yubikey-sam" ''
        #!${pkgs.stdenv.shell}
        ${pkgs.sudo}/bin/sudo -u sam ${clearYubikey}
      '';
    in ''
      ACTION=="add|change", SUBSYSTEM=="usb", ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0407", RUN+="${clearYubikeySam}"
      SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="1b7c", MODE="0660", TAG+="uaccess", TAG+="udev-acl"
      SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="2b7c", MODE="0660", TAG+="uaccess", TAG+="udev-acl"
      SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="3b7c", MODE="0660", TAG+="uaccess", TAG+="udev-acl"
      SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="4b7c", MODE="0660", TAG+="uaccess", TAG+="udev-acl"
      SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="1807", MODE="0660", TAG+="uaccess", TAG+="udev-acl"
      SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="1808", MODE="0660", TAG+="uaccess", TAG+="udev-acl"
      SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0000", MODE="0660", TAG+="uaccess", TAG+="udev-acl"
      SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0001", MODE="0660", TAG+="uaccess", TAG+="udev-acl"
      SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0004", MODE="0660", TAG+="uaccess", TAG+="udev-acl"
      KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0660", GROUP="plugdev", ATTRS{idVendor}=="2c97"
      KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0660", GROUP="plugdev", ATTRS{idVendor}=="2581"
    '';
    udev.packages = [pkgs.yubikey-personalization];
    openssh = {
      settings.PasswordAuthentication = false;
      enable = true;
    };

    desktopManager.gnome.enable = true;
    displayManager.gdm = {
      enable = true;
      wayland = true;
    };
  };
  # Open ports in the firewall.
  networking.firewall.allowedTCPPorts = [3001 9090 9093 3000 3100];
  networking.firewall.allowedUDPPorts = [
    7777
    7778
    7787
    7788
    7797
    7798
    27015
    27016
    27017
  ];
  # TODO: pull users from secrets.nix instead
  users.users.sam = {
    uid = 10016;
    isNormalUser = true;
    extraGroups = ["wheel"]; # Enable ‘sudo’ for the user.
    openssh.authorizedKeys.keys = ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDEPOLnk4+mWNGOXd309PPxal8wgMzKXHnn7Jbu/SpSUYEc1EmjgnrVBcR0eDxgDmGD9zJ69wEH/zLQLPWjaTusiuF+bqAM/x7z7wwy1nZ48SYJw3Q+Xsgzeb0nvmNsPzb0mfnpI6av8MTHNt+xOqDnpC5B82h/voQ4m5DGMQz60ok2hMeh+sy4VIvX5zOVTOFPQqFR6BGDwtALiP5PwMfyScYXlebWHhDRdX9B0j9t+cqiy5utBUsl4cIUInE0KW7Z8Kf6gIsmQnfSZadqI857kdozU3IbaLoJc1C6LyVjzPFyC4+KUC11BmemTGdCjwcoqEZ0k5XtJaKFXacYYXi1l5MS7VdfHldFDZmMEMvfJG/PwvXN4prfOIjpy1521MJHGBNXRktvWhlNBgI1NUQlx7rGmPZmtrYdeclVnnY9Y4HIpkhm0iEt/XUZTMQpXhedd1BozpMp0h135an4uorIEUQnotkaGDwZIV3mSL8x4n6V02Qe2CYvqf4DcCSBv7D91N3JplJJKt7vV4ltwrseDPxDtCxXrQfSIQd0VGmwu1D9FzzDOuk/MGCiCMFCKIKngxZLzajjgfc9+rGLZ94iDz90jfk6GF4hgF78oFNfPEwoGl0soyZM7960QdBcHgB5QF9+9Yd6QhCb/6+ENM9sz6VLdAY7f/9hj/3Aq0Lm4Q=="];
  };
  users.users.root = {
    openssh.authorizedKeys.keys = [
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDEPOLnk4+mWNGOXd309PPxal8wgMzKXHnn7Jbu/SpSUYEc1EmjgnrVBcR0eDxgDmGD9zJ69wEH/zLQLPWjaTusiuF+bqAM/x7z7wwy1nZ48SYJw3Q+Xsgzeb0nvmNsPzb0mfnpI6av8MTHNt+xOqDnpC5B82h/voQ4m5DGMQz60ok2hMeh+sy4VIvX5zOVTOFPQqFR6BGDwtALiP5PwMfyScYXlebWHhDRdX9B0j9t+cqiy5utBUsl4cIUInE0KW7Z8Kf6gIsmQnfSZadqI857kdozU3IbaLoJc1C6LyVjzPFyC4+KUC11BmemTGdCjwcoqEZ0k5XtJaKFXacYYXi1l5MS7VdfHldFDZmMEMvfJG/PwvXN4prfOIjpy1521MJHGBNXRktvWhlNBgI1NUQlx7rGmPZmtrYdeclVnnY9Y4HIpkhm0iEt/XUZTMQpXhedd1BozpMp0h135an4uorIEUQnotkaGDwZIV3mSL8x4n6V02Qe2CYvqf4DcCSBv7D91N3JplJJKt7vV4ltwrseDPxDtCxXrQfSIQd0VGmwu1D9FzzDOuk/MGCiCMFCKIKngxZLzajjgfc9+rGLZ94iDz90jfk6GF4hgF78oFNfPEwoGl0soyZM7960QdBcHgB5QF9+9Yd6QhCb/6+ENM9sz6VLdAY7f/9hj/3Aq0Lm4Q== samuel.leathers@iohk.io"
    ];
    shell = pkgs.lib.mkOverride 50 "${pkgs.bashInteractive}/bin/bash";
  };

  security.polkit.extraConfig = ''
    polkit.addRule(function(action, subject) {
        if (action.id == "org.freedesktop.login1.suspend" ||
            action.id == "org.freedesktop.login1.suspend-multiple-sessions" ||
            action.id == "org.freedesktop.login1.hibernate" ||
            action.id == "org.freedesktop.login1.hibernate-multiple-sessions")
        {
            return polkit.Result.NO;
        }
    });
  '';

  system.activationScripts.starship = let
    starshipConfig = pkgs.writeText "starship.toml" ''
      [username]
      show_always = true
      [hostname]
      ssh_only = true
      [git_commit]
      tag_disabled = false
      only_detached = false
      [memory_usage]
      format = "via $symbol[''${ram_pct}]($style) "
      disabled = false
      threshold = -1
      [time]
      format = '[\[ $time \]]($style) '
      disabled = false
      [[battery.display]]
      threshold = 100
      style = "bold green"
      [[battery.display]]
      threshold = 50
      style = "bold orange"
      [[battery.display]]
      threshold = 20
      style = "bold red"
      [status]
      map_symbol = true
      disabled = false
    '';
  in {
    text = ''
      mkdir -p /etc/per-user/shared
      cp ${starshipConfig} /etc/per-user/shared/starship.toml
      mkdir -p /home/sam/.config
      mkdir -p /root/.config
      chown sam:users /home/sam/.config
      chown root /root/.config
      ln -sf /etc/per-user/shared/starship.toml /home/sam/.config/starship.toml
      ln -sf /etc/per-user/shared/starship.toml /root/.config/starship.toml
    '';
    deps = [];
  };

  powerManagement.enable = false;
  # This value determines the NixOS release with which your system is to be
  # compatible, in order to avoid breaking some software such as database
  # servers. You should change this only after NixOS release notes say you
  # should.
  system.stateVersion = "25.05"; # Did you read the comment?
}
