# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "zpool/nixos/root";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "zpool/nixos/nix";
    fsType = "zfs";
  };

  fileSystems."/etc" = {
    device = "zpool/nixos/etc";
    fsType = "zfs";
  };

  fileSystems."/var" = {
    device = "zpool/nixos/var";
    fsType = "zfs";
  };

  fileSystems."/var/lib" = {
    device = "zpool/nixos/var/lib";
    fsType = "zfs";
  };

  fileSystems."/var/log" = {
    device = "zpool/nixos/var/log";
    fsType = "zfs";
  };

  fileSystems."/var/spool" = {
    device = "zpool/nixos/var/spool";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "zpool/userdata/home";
    fsType = "zfs";
  };

  fileSystems."/root" = {
    device = "zpool/userdata/home/root";
    fsType = "zfs";
  };

  fileSystems."/home/sam" = {
    device = "zpool/userdata/home/sam";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/37bfa90b-2926-4154-8529-56fc233604aa";
    fsType = "ext4";
  };

  swapDevices = [];
}
