# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zpool/nixos/root";
      fsType = "zfs";
    };

  fileSystems."/etc" =
    { device = "zpool/nixos/etc";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "zpool/nixos/nix";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "zpool/nixos/var";
      fsType = "zfs";
    };

  fileSystems."/var/log" =
    { device = "zpool/nixos/var/log";
      fsType = "zfs";
    };

  fileSystems."/var/spool" =
    { device = "zpool/nixos/var/spool";
      fsType = "zfs";
    };

  fileSystems."/root" =
    { device = "zpool/userdata/home/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zpool/userdata/home";
      fsType = "zfs";
    };

  fileSystems."/home/sam" =
    { device = "zpool/userdata/home/sam";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8833-E9D5";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5a023e24-48db-4bc5-ba6d-f026cbf54abd"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp200s0f4u1u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wg0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
