# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zpool/root/nixos";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "zpool/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zpool/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/04F6-2233";
      fsType = "vfat";
    };

  fileSystems."/ubuntu" =
    { device = "zpool/root/ubuntu";
      fsType = "zfs";
    };

  fileSystems."/ubuntu/boot" =
    { device = "/boot";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/ubuntu/dev" =
    { device = "devtmpfs";
      fsType = "devtmpfs";
    };

  fileSystems."/ubuntu/proc" =
    { device = "proc";
      fsType = "proc";
    };

  fileSystems."/ubuntu/sys" =
    { device = "sysfs";
      fsType = "sysfs";
    };

  fileSystems."/ubuntu/run" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/903ca9fa-bbc8-4c18-8cc6-befdd6789778"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
